"""Render a job as a Markdown or HTML report."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path


def render_markdown(job: dict, findings: list | None = None) -> str:
    lines = []
    lines.append("# WHAXON Report")
    lines.append("")
    lines.append(f"**Job ID:** `{job.get('id', '')}`  ")
    lines.append(f"**Tool:** `{job.get('tool', '')}`  ")
    lines.append(f"**Target:** `{job.get('target', '')}`  ")
    lines.append(f"**Status:** {job.get('status', '')}  ")
    lines.append(f"**Exit code:** {job.get('exit_code', '')}  ")
    dur = job.get("duration_s") or 0
    lines.append(f"**Duration:** {dur:.2f}s  ")
    lines.append("")

    findings = findings or []
    lines.append("## Summary")
    lines.append("")
    lines.append(f"Found **{len(findings)}** finding(s).")
    _with_cvss = [f for f in findings if f.get("cvss") is not None]
    if _with_cvss:
        _top = max(f["cvss"] for f in _with_cvss)
        lines.append(f"Highest CVSS: **{_top}**")
    lines.append("")

    if findings:
        by_sev: dict[str, int] = {}
        for f in findings:
            s = f.get("severity", "info")
            by_sev[s] = by_sev.get(s, 0) + 1
        lines.append("| Severity | Count |")
        lines.append("| --- | --- |")
        for sev in ("critical", "high", "medium", "low", "info"):
            if sev in by_sev:
                lines.append(f"| {sev} | {by_sev[sev]} |")
        lines.append("")
        lines.append("## Findings")
        lines.append("")
        for i, f in enumerate(findings, 1):
            lines.append(f"### {i}. {f.get('kind', '')} \u2014 {f.get('severity', '')}")
            lines.append("")
            d = f.get("data") or {}
            for k, v in d.items():
                lines.append(f"- **{k}:** `{v}`")
            if f.get("cvss") is not None:
                lines.append(f"- **CVSS:** `{f['cvss']}`")
            if f.get("cwe"):
                lines.append(f"- **CWE:** `{f['cwe']}`")
            if f.get("impact"):
                lines.append("")
                lines.append(f"**Impact:** {f['impact']}")
            if f.get("remediation"):
                lines.append("")
                lines.append(f"**Remediation:** {f['remediation']}")
            if f.get("raw_line"):
                lines.append("")
                lines.append(f"> `{f['raw_line'].strip()}`")
            lines.append("")

    lines.append("## Raw Output")
    lines.append("")
    lines.append("```")
    for line in job.get("lines", []):
        prefix = "[err] " if line.get("stream") == "stderr" else ""
        lines.append(prefix + line.get("text", ""))
    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append(f"_Generated by WHAXON on {datetime.now(timezone.utc).isoformat()}_")
    lines.append("")
    return "\n".join(lines)


def render_html(job: dict, findings: list | None = None) -> str:
    """Render a job as a standalone HTML report."""
    import html as _html
    md = render_markdown(job, findings)
    try:
        import markdown as _md
        body = _md.markdown(md, extensions=["tables", "fenced_code", "nl2br"])
    except ImportError:
        body = "<pre>" + _html.escape(md) + "</pre>"
    style = (
        "body{font:15px/1.6 system-ui,sans-serif;max-width:900px;margin:2em auto;padding:0 1.5em;color:#e8eef7;background:#0d121a}"
        "h1,h2,h3{color:#7dc0ff;margin-top:1.4em}a{color:#7dc0ff}"
        "code{background:#0a0f16;padding:2px 6px;border-radius:4px;font-family:ui-monospace,monospace;font-size:0.92em}"
        "pre{background:#0a0f16;padding:1em;border-radius:8px;overflow:auto;border:1px solid #2c3a4d;font-family:ui-monospace,monospace}"
        "pre code{background:none;padding:0}table{border-collapse:collapse;margin:1em 0}"
        "th,td{border:1px solid #2c3a4d;padding:6px 12px;text-align:left}th{background:#151e2b}"
        "blockquote{border-left:3px solid #7dc0ff;margin:1em 0;padding:0 1em;color:#a6b4c8;background:#111925;border-radius:0 6px 6px 0}"
    )
    return (
        "<!doctype html><html><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        "<title>WHAXON Report</title><style>" + style + "</style></head><body>" + body + "</body></html>"
    )
