"""Render a job as a Markdown or HTML report."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path


def render_markdown(job: dict, findings: list | None = None) -> str:
    lines = []
    lines.append("# WHAXON Report")
    lines.append("")
    lines.append(f"**Job ID:** `{job.get('id', '')}`  ")
    lines.append(f"**Tool:** `{job.get('tool', '')}`  ")
    lines.append(f"**Target:** `{job.get('target', '')}`  ")
    lines.append(f"**Status:** {job.get('status', '')}  ")
    lines.append(f"**Exit code:** {job.get('exit_code', '')}  ")
    dur = job.get("duration_s") or 0
    lines.append(f"**Duration:** {dur:.2f}s  ")
    lines.append("")

    findings = findings or []
    lines.append("## Summary")
    lines.append("")
    lines.append(f"Found **{len(findings)}** finding(s).")
    lines.append("")

    if findings:
        by_sev: dict[str, int] = {}
        for f in findings:
            s = f.get("severity", "info")
            by_sev[s] = by_sev.get(s, 0) + 1
        lines.append("| Severity | Count |")
        lines.append("| --- | --- |")
        for sev in ("critical", "high", "medium", "low", "info"):
            if sev in by_sev:
                lines.append(f"| {sev} | {by_sev[sev]} |")
        lines.append("")
        lines.append("## Findings")
        lines.append("")
        for i, f in enumerate(findings, 1):
            lines.append(f"### {i}. {f.get('kind', '')} \u2014 {f.get('severity', '')}")
            lines.append("")
            d = f.get("data") or {}
            for k, v in d.items():
                lines.append(f"- **{k}:** `{v}`")
            raw = f.get("raw_line")
            if raw:
                lines.append("")
                lines.append(f"> `{raw.strip()}`")
            lines.append("")

    lines.append("## Raw Output")
    lines.append("")
    lines.append("```")
    for line in job.get("lines", []):
        prefix = "[err] " if line.get("stream") == "stderr" else ""
        lines.append(prefix + line.get("text", ""))
    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append(f"_Generated by WHAXON on {datetime.now(timezone.utc).isoformat()}_")
    lines.append("")
    return "\n".join(lines)


def render_html(job: dict, findings: list | None = None) -> str:
    import html as _html
    md = render_markdown(job, findings)
    style = (
        "body{font:14px/1.5 system-ui;max-width:900px;margin:2em auto;padding:0 1em;"
        "color:#e8eef7;background:#0d121a}"
        "pre{background:#0a0f16;padding:1em;border-radius:8px;overflow:auto;"
        "border:1px solid #2c3a4d;white-space:pre-wrap}"
    )
    return (
        "<!doctype html><html><head><meta charset='utf-8'>"
        "<title>WHAXON Report</title>"
        f"<style>{style}</style></head><body><pre>"
        + _html.escape(md)
        + "</pre></body></html>"
    )
